abusix/hailstorm

- src/components/form-field/text-input/text-input.tsx
Fixed a small issue with different heights between text input fields and list boxes:
Before:
> fix(form): height issue between listbox and text input fields

- src/components/alert/index.ts
- src/components/form-field/form-field-group.tsx
- src/components/index.ts
- src/components/tab/tab-button.tsx
- src/components/tab/tab-panel.tsx
- src/components/table-virtualized/index.ts
- src/components/table-virtualized/table-virtualized.tsx
This MR fixes some more import/types issues that occurs when running `npm run build`. 
Also added exports to `AlertIntent` and `TableVirtualizedProp` interfaces.
> Pla 321 integrate the new hailstorm npm package into frontend v2

- tailwind.config.cjs
This MR adds missing colors from the badge component to the tailwind.config.js file
> fix(tailwind): add missing tailwind colors required by the badge component

- src/components/form-field/single-combobox/single-combobox-input.tsx
- src/components/form-field/single-combobox/single-combobox.stories.tsx
- src/components/form-field/single-combobox/single-combobox.tsx
> BREAKING CHANGE: The combobox display value changed to function

- .github/workflows/release.yml
- .github/workflows/test.yaml
- jest.config.js
- package-lock.json
- package.json
- src/components/alert/alert.test.tsx
- tsconfig.json
- vite.config.ts
- vitest-setup.ts
Adding Vitest and a new action for automated testing. This PR only adds one component test for testing reasons.
> feat(chore): add test execution

- src/components/form-field/text-input/text-input.stories.tsx
- src/components/form-field/text-input/text-input.tsx
This PR fixes the left icon issue not being displayed in the text input component
Before
Now
> fix(input): Fix left icon not being displayed in the text-input

- src/components/badge/badge.test.tsx
This PR adds a test to the badge component. It covers string representation and component shape.
> feat(chore): add badge test

- src/components/form-field/multi-combobox/multi-combobox-options.tsx
Added z-index to multi-combobox options to fix the issue shown in the image:
> fix(multi-combobox-options): Add z-index to multicombobox options

- .eslintrc.cjs
- src/components/button/button.stories.tsx
- src/components/button/button.test.tsx
- src/components/button/button.tsx
This PR will change the general interface of a button. The interface implements the default native props and doesn't use the reserved native props.
> feat(component): use native props for button

- src/components/alert/alert.tsx
This PR fixes an issue with the intent icon that shrinks unintended when text is too long in the alert description.
> fix(components): prevent alert icon to shrink

- src/components/form-field/textarea/textarea.tsx
- src/components/skeleton/skeleton.tsx
This PR adds minimum height to the `textarea` component
> feat(textarea): add minimum height

- src/components/dialog/dialog.stories.tsx
- src/components/dialog/dialog.tsx
Remove the fallback buttons when not passing a footer, plus a style fix.
Expand storybook to see the dialog used with different options.
> PLA-764 Remove the default footer from the dialog component

- package-lock.json
- package.json
- src/components/button/button.stories.tsx
- src/components/button/button.tsx
We are adding the "as"-prop to the button to support anchor tags styled as a normal button.
Note: need to bump up the version of tailwind prettier plugin since prettier has some breaking changes.
> feat(components): add support for anchor tag buttons

- src/components/dialog/dialog.tsx
We removed the width and height of the dialog panel component since this is supported through the normal className prop. Beside that the dynamic props 
```
height ? `h-[${height}px]` : "max-h-full",
width ? `w-[${width}px]` : "w-[592px]",
```
are not working in production because it is no purgeable HTML.
We also increased the general width of the dialog.
> BREAKING CHANGE: Remove width and height from dialog parent element

- src/components/form-field/text-input/text-input.stories.tsx
- src/components/form-field/text-input/text-input.tsx
We change the background of read only text inputs to a soft primary color.
> fix(components): use correct background on read only inputs

- src/components/navigation/navigation-disclosure.tsx
Pass the HeadlessUI close function to children as function children.
> feat(components): pass close function to disclosure root component

- .storybook/preview.ts
- src/components/navigation/navigation-popover.tsx
- src/components/navigation/navigation.stories.tsx
- src/components/navigation/navigation.tsx
Add navigation popover to Navigation component:
This is how it will look implemented (I used the next branch to publish the package in the next channel)
> feat(NavigationPopover): Add navigation popover to Navigation component

- package-lock.json
- package.json
- src/components/navigation/navigation-popover-button.tsx
- src/components/navigation/navigation-popover-context.tsx
- src/components/navigation/navigation-popover-panel.tsx
- src/components/navigation/navigation-popover.tsx
- src/components/navigation/navigation.stories.tsx
- src/components/navigation/navigation.tsx
This PR implements the lib `react-popper` to handle in a better way the positioning of the popover as suggested on the [headless-ui documentation](https://headlessui.com/react/popover#positioning-the-panel).
> fix(NavigationPopover): use react-popper for handling in a better way the positioning

- src/components/navigation/navigation-disclosure-panel.tsx
We need to use a normal div element to solve invalid html. Usually this items should link to another page and this would create a button inside an anchor tag.
> fix(components): use div instead of button to fix invalid html

- src/components/navigation/navigation-popover-button.tsx
Add onClick prop to navigations popover item to support custom behavior for navigation items.
> feat(components): add onClick prop

- package-lock.json
- package.json
Overwrite adobe/css-tools used by jest-dom.
> fix(dependencies): overwrite adobe/css-tools for jest-dom

- src/components/form-field/listbox/listbox-button-text-value.tsx
- src/components/form-field/listbox/listbox-button.tsx
Add styling for focus and open state.
> fix(components): style open state

- src/components/tooltip/tooltip-portal.tsx
- src/components/tooltip/tooltip.tsx
This PR adds the option of wrapping the tooltip inside a portal to fix some edge use cases.
> fix(Tooltip): add strategy option to support edge use cases

- src/components/button-group/button-group.stories.tsx
- src/components/button-group/button-group.tsx
- src/components/button-group/index.tsx
- src/components/index.ts
> feat(components): add ButtonGroup component

- src/components/form-field/radio-box/radio-box-option.tsx
- src/components/form-field/radio-box/radio-box.stories.tsx
This mr:
- fixes a transparent bg issue with radio box options
- improves classNames in radio box option
- adds a `className` property to radio box options 
- BREAKING CHANGE: This mr adds a breaking change where the text-size class got removed
> Fix Radio Box Issues

- src/components/tab/tab-panels.tsx
Add className prop to tab panels wrapper.
> fix(components): pass className prop to tab panels wrapper

- package-lock.json
- package.json
- src/components/dialog/dialog.stories.tsx
- src/components/panel/panel.stories.tsx
- src/components/toggle/toggle.stories.tsx
- src/components/toggle/toggle.tsx
Add HeadlessUIs Switch.Group and Switch.Layout to support custom clickable labels.
Compatibility:
The switch can also be used without any label e.g. forms.
> BREAKING CHANGE(components): use switch group to support switch label

- src/components/disclosure/disclosure.tsx
- Adjust disclosure button height
> fix(components): adjust disclosure button height

- src/components/form-field/radio-box/radio-box-option.tsx
This mr removes an unwanted gap between labels and descriptions of radio box option content/children
> fix: removed gap-2 in radio boxes option

- src/components/navigation/navigation-disclosure-panel.tsx
- src/components/navigation/navigation-disclosure.tsx
- src/components/navigation/navigation-group.tsx
- src/components/navigation/navigation-popover-button.tsx
This mr adds just cursor-pointer classes to nav elements :-)
> Pla 975 add cursor pointer to nav

- src/components/tab/tab-panel.tsx
Remove the `as={React.Fragment}` prop, as this will throw a console error when headless ui attempts to pass down some basic HTML attributes.
> fix(TabPanel): Remove as={React.Fragment} prop

- src/components/form-field/listbox/listbox-option.tsx
- Fix active state if Listbox is nested inside a tab component.
> chore: update ListboxOption component to use render prop for dynamic styling

- src/components/tooltip/tooltip.tsx
- return fragment for tooltip instead of div
> fix(components): use fragment for tooltip return value

- .eslintrc.cjs
- src/components/button/button.stories.tsx
- src/components/index.ts
- src/components/link/index.tsx
- src/components/link/link.stories.tsx
- src/components/link/link.tsx
- src/components/slot/slot.tsx
- split Button/Link component into two independent components
- support asChild prop for links (e.g. Next/Link can be used now)
> BREAKING CHANGE: split button/link component and support asChild for links

- src/components/alert/alert.tsx
- extend alert interface with 'div' component props
> feat: extend alert interface with div props

- src/components/navigation/navigation-disclosure.tsx
- src/components/navigation/navigation-group.tsx
- src/components/navigation/navigation.stories.tsx
decrease the gap so abusehq fits in bold
Also allow passing classes to override styles.
> navigation spacing fix

- src/components/form-field/listbox/listbox-button.tsx
We remove the ui-open state that gets applied when a listbox is inside a model/dialog. The ui-open state is always `true` when the outer dialog is in open state. This causes an always active ui-open state visually.
https://headlessui.com/v1/react/listbox#focus-management
The focus state is intended to get trapped and ui-open is not supported on the Listbox.Button component.
> fix: remove unsupported ui-open class from Listbox button

- src/components/tooltip/tooltip.tsx
Instead of rendering a div around the child that causes layout issues, we now rendering the passed children with the ref for popper.
> fix: render passed children in tooltip parent

- src/components/dialog/dialog.tsx
- src/components/icon-button/icon-button.stories.tsx
- src/components/icon-button/icon-button.tsx
- src/components/table-virtualized/table-virtualized.stories.tsx
BREAKING CHANGE: the type property was renamed to "variant", IconButtons extends now the native ButtonHTMLAttributes
> Improve Hailstorm's IconButton properties

- src/components/table-unvirtualized/table-body/table-body-row/table-body-row.tsx
To support `onClick` we need to pass it to the component. We already pass the `HTMLTableRowElement` but not using all props here. Just pass the rest props and it should be fine.
> fix: pass missing props to table row

- src/components/popover-menu/popover-menu-panel.tsx
- src/components/popover-menu/popover-menu.tsx
> feat(PopoverMenu): make PopoverMenu to take Headless ui Popover props

- src/components/badge/badge.stories.tsx
- src/components/badge/badge.tsx
Badge component needs custom styling for a new feature. Added className optional property to overwrite existing tailwind classes
> chore(Badge): Allow custom className on Badge component

- .releaserc
- package.json
- pnpm-lock.yaml
We will no longer set the package version in the repo as part of the
release. Instead it will be left as `0.0.0` and the semantic-release
package will set it before publishing based on tags.
This is based on the official recommendation of the semantic-release
documentation.
> Remove @semantic-release/git

- .devcontainer/devcontainer.json
- .github/workflows/release.yml
- **chore(dev): Add Github actions extension to dev container configuration**
- **feat(build): Publish to github in addition to npm**
We already use the @abusix scope for packages for various private packages. We now have a clash in one of our apps as we are trying to install one of these github packages and hailstorm (via npm) in the same project.
Unfortunately pnpm does not support mixing and matching registries within a single scope. So the most inobtrustive option is simply to publish to both registries.
> Deploy to GitHub registry
