src/components/menu/menu-item/menu-item.stories.tsx

- use Menu component surrounding inside the render function to fix to many hook renderings

fix(components): use Menu inside render function

---

src/components/button/button.tsx
src/components/last-changed-info/last-changed-info.stories.tsx
src/components/sidesheet/sidesheet-panel-header.tsx
src/components/sidesheet/sidesheet.stories.tsx
src/components/sidesheet/sidesheet.tsx
src/components/spinner/spinner.stories.tsx
src/components/tab/tab.stories.tsx
src/components/tag/tag.stories.tsx
src/components/toast/toast.stories.tsx
src/components/toggle/toggle.stories.tsx
src/components/toggle/toggle.tsx
src/util/storybook-utils.ts

This PR adds some minor documentation fixes and components fixes:
- Buttons were not displaying their Icons:
- Before 
- Now
- Last Changed Info docs
- Before
- Now
- Sidesheet had minor issues with the z-index and the spacing between elements
- Before
- Now
- Spinner docs: 
- Before
- Now
- Tab docs: 
- Before
- Now
- Toast docs: 
- Before
- Now
- Toggle docs:
- Before:
- Now

fix: minor storybook docs and component fixes

---

src/components/toast/toast.tsx

fix(toast): Delete unnecessary hidden class

---

src/styles/styles.scoped.css

Fix missing `.tw-root` class in scoped styles file

fix(styles): Fix missing .tw-root class in scoped styles file

---

src/components/button/button.tsx
src/components/form-field/text-input/text-input.tsx

Add a couple of extra props to `Button` and `TextInput` components.

fix(input): Add props to input and button

---

.github/workflows/auto-author-assign.yml

Add auto assignee for authors.

fix(actions): add auto author assign to actions

---

src/components/avatar/avatar.test.tsx

This PR adds a test to the avatar component.

feat(chore): add avatar test

---

.github/workflows/test.yaml
src/components/button/button.test.tsx

feat(chore): add button test

---

src/components/dialog/dialog.tsx
src/components/section/section.stories.tsx
src/components/table-unvirtualized/table-unvirtualized.stories.tsx
src/components/table-virtualized/table-virtualized.stories.tsx

The button got a new interface and needs to be fixed in all references.

Pla 696 hailstorm improve button interfaces fix buttons

---

.github/workflows/type-check.yaml

This PR adds an action to check ts types and will break when there is an error.

feat(actions): add type check action

---

package.json
src/components/table-unvirtualized/table-body/table-body-row/table-body-row.tsx

this mr adds the border-bottom to the last table row element of a table

Pla 709 UI improvements

---

src/components/form-field/text-input/text-input.stories.tsx
src/components/form-field/text-input/text-input.tsx

Add native props for input element

feat(component): use native props for input

---

tailwind.config.cjs

Adding a missing tailwind config value for width.

fix(config): add missing config value

---

src/components/navigation/navigation-group.tsx

Forward all props to navigation item to support click events.

feat(components): forward all props to navigation item

---

src/components/navigation/navigation-popover-panel.tsx

Add hover state for navigation popover items.

fix(components): add hover state to popover nav items

---

package-lock.json
package.json

Remove rollup-plugin-tailwindcss.

fix(dependencies): remove unused rollup plugin

---

package-lock.json
package.json

Update jest-dom to remove vulnerab overwrite.

fix(dependencies): update jest-dom version

---

src/components/disclosure/disclosure.stories.tsx
src/components/disclosure/disclosure.tsx
src/components/disclosure/index.tsx
src/components/index.ts

feat(components): add disclosure component

---

.github/workflows/build.yml

Add build step to cd pipeline.

fix(ci/cd): add build step to pipeline

---

src/components/menu/menu-button/menu-button.tsx

Render menu button as div to support all children syntax.

feat(components): adjust menu button to be div

---

src/components/disclosure/disclosure.stories.tsx
src/components/disclosure/disclosure.tsx

Pass defaultOpen state to headless disclosure parent component.

fix(components): pass defaultOpen state to disclosure parent

---

src/components/disclosure/disclosure.tsx

Use padding and calculated height by its text height + padding instead of fixed height.

fix(components): increase padding and remove fixed height

---

src/components/badge/index.ts
src/components/index.ts

Export badge type to support usage in apps. e.g. map specific colors to words and support correct typing.

feat(components): export badge type to support usage in apps

---

src/components/badge/badge.stories.tsx
src/components/badge/badge.tsx
tailwind.config.cjs

- Add new color purple
- Adjust green background color

feat(components): adjust badge colors

---

src/components/disclosure/disclosure.tsx

Add missing focus state for disclosure button.

fix(components): add missing focus outline

---

src/components/button-group/button-group.tsx

- Increase button group label size and weight

fix(components): increase buttin group label size and weight

---

src/components/featured-tag/index.ts
src/components/index.ts

This mr adds export for featured tag component

fix: added feature tag export

---

src/styles/global-styles.stories.tsx
src/styles/index.css
src/styles/styles.scoped.css
tailwind.config.cjs

This mr fixs some styling of inline-link className and adds a className overview to storybook

Pla 996 hailstorm fix inline link css style

---

src/components/form-field/radio-box/radio-box.stories.tsx
src/components/form-field/radio-box/radio-box.tsx

- Remove default orientation for radio box

BREAKING CHANGE: remove default radio box orientation

---

src/components/form-field/listbox/listbox-option.tsx
src/components/form-field/listbox/listbox.stories.tsx

This mr adds the new disabled state to listbox option elements. I also split up the big className string into multiple semmantical sub states / classNames. Please also take a look at this, because I don’t know if we would want to have it :-)

feat: added disabled listbox state

---

src/styles/index.css
src/styles/styles.scoped.css

https://linear.app/abusix/issue/PLA-1026/abuse-dashboard-change-color-of-events-link

fix: updated colors for inline links

---

src/components/button/button.tsx

- add underline to minimal button due to new design

fix(components): add underline style to minimal button

---

src/components/form-field/form-field-label.tsx
src/components/form-field/text-input/text-input.stories.tsx

also adds a little story example for optional labels

Fix color of optional formfield labels to be text-neutral-800

---

src/components/navigation/navigation-disclosure.tsx
src/components/navigation/navigation-group-item-tag.tsx
src/components/navigation/navigation-group.tsx
src/components/navigation/navigation.stories.tsx

- add prop to display custom tags next to the navigation item text

feat(components): add tag prop to main disclosure button

---

package-lock.json
package.json

- update jsdom to newest version

fix(dependencies): update jsdom

---

src/components/navigation/navigation.stories.tsx

I forgot that semantic release needs semantic commit messages.
This is a trigger to release a new version covering aforementioned fix. It also covers updating development tools like storybook

Force release

---

src/components/index.ts
src/components/popover-menu/index.ts

sorry rodrigo, i’ve missed the exports -.- :D

fix: added missing export -.-

---

src/components/popover-menu/popover-menu-panel-divider.tsx
src/components/popover-menu/popover-menu-panel-group.tsx
src/components/popover-menu/popover-menu-panel-item.tsx
src/components/popover-menu/popover-menu-panel-title.tsx
src/components/popover-menu/popover-menu-panel.tsx
src/components/popover-menu/popover-menu.stories.tsx

Added Divider, Group, Title to Popover Menu

---

src/components/popover-menu/popover-menu.stories.tsx

- sort imports
Current changes in 5.8.0 are not pushed to npm and we need trigger a rebuild to check if it is working again.

fix: sort imports

---

src/components/form-field/listbox/listbox-button.tsx
src/components/form-field/listbox/listbox.stories.tsx

feat: added disabled option/styles to listboxes

---

src/components/form-field/multi-combobox/multi-combobox-input.tsx

feat: receive property disabled in multi-combobox input

---

src/components/form-field/multi-combobox/multi-combobox-input.tsx

I had forgotten to add the disabled styles to my last change 😓

fix(MultiComboboxInput): add disabled styles

---

src/components/table-unvirtualized/table-body/table-body-placeholder/table-body-placeholder.tsx

fix(TableEmptyPlaceholder):Remove max width from table empty placehoder

---

src/components/form-field/text-input/text-input.tsx

fix(TextInput): support date as type

---

src/components/form-field/text-input/text-input.tsx

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local

feat: added type "datetime-local" to TextInput fields

---

src/components/index.ts
src/components/table-key-value-pair/index.ts
src/components/table-key-value-pair/table-key-value-pair-body-key-cell.tsx
src/components/table-key-value-pair/table-key-value-pair-body-row.tsx
src/components/table-key-value-pair/table-key-value-pair-body-value-cell.tsx
src/components/table-key-value-pair/table-key-value-pair-body.tsx
src/components/table-key-value-pair/table-key-value-pair-header.tsx
src/components/table-key-value-pair/table-key-value-pair.stories.tsx
src/components/table-key-value-pair/table-key-value-pair.tsx
src/components/table-unvirtualized/table-body/table-body-placeholder/table-body-placeholder.tsx

https://github.com/user-attachments/assets/7c37c9f3-177b-499b-9b2a-7a0086b09fb3

feat: added table for key-value pair columns

---

.vscode/settings.json
src/components/tab/tab-panel.tsx

feat(TabPanel): accept all headless ui props
